"""empty message

Revision ID: 1df363a81175
Revises: 3349de849478
Create Date: 2020-05-22 00:00:26.921610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df363a81175'
down_revision = '3349de849478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'tr_geoid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('tr_geoid', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
