"""empty message

Revision ID: 3349de849478
Revises: 4fdf579f401d
Create Date: 2020-05-21 23:52:24.040074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3349de849478'
down_revision = '4fdf579f401d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_column('address', 'logitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('logitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('address', 'longitude')
    # ### end Alembic commands ###
