"""empty message

Revision ID: 991facde634b
Revises: 512bd45f4b23
Create Date: 2020-05-24 00:52:58.734587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991facde634b'
down_revision = '512bd45f4b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('zip', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'zip')
    # ### end Alembic commands ###
